// Auto-generated by PlatformIO build script
// DO NOT EDIT MANUALLY

#ifndef GIT_INFO_H
#define GIT_INFO_H

#define GIT_COMMIT_HASH_FULL "a3b095621db13cc1ead884b62a6eb42d712bba52"
#define GIT_COMMIT_HASH_SHORT "a3b0956"
#define GIT_BRANCH "ST7305-ESP32S3-dev"
#define GIT_DESCRIBE "ST7305-v0.0.1-103-ga3b0956"
#define GIT_IS_DIRTY true

#endif // GIT_INFO_H
