// Auto-generated by PlatformIO build script
// DO NOT EDIT MANUALLY

#ifndef GIT_INFO_H
#define GIT_INFO_H

#define GIT_COMMIT_HASH_FULL "6596a069a374922cdad8b50bba08c2e7a36e7493"
#define GIT_COMMIT_HASH_SHORT "6596a06"
#define GIT_BRANCH "ST7305-ESP32S3-dev"
#define GIT_DESCRIBE "ST7305-v0.0.1-98-g6596a06"
#define GIT_IS_DIRTY true

#endif // GIT_INFO_H
