// Auto-generated by PlatformIO build script
// DO NOT EDIT MANUALLY

#ifndef GIT_INFO_H
#define GIT_INFO_H

#define GIT_COMMIT_HASH_FULL "3ce9c0a7d01e755f7868f4059f770b55b8037283"
#define GIT_COMMIT_HASH_SHORT "3ce9c0a"
#define GIT_BRANCH "ST7305-ESP32S3-dev"
#define GIT_DESCRIBE "ST7305-v0.0.1-99-g3ce9c0a"
#define GIT_IS_DIRTY true

#endif // GIT_INFO_H
